api_secret_key = "<configure me>" # fill this in!

[destination.bigquery]
location = "US"

[destination.bigquery.credentials]
project_id = "<configure me>" # fill this in!
private_key = "<configure me>" # fill this in!
client_email = "<configure me>" # fill this in!
